name: End to End Tests

on:

  schedule:
    - cron: '*/15 * * * *'

jobs:

  e2e:
    name: End to end test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install development tools
        run: npm install
      - name: Run e2e tests
        run: npm run test
